
// import { Temp } from "@/components/temp";
import Navbar from "@/components/common/Navbar/Navbar";
import ContactSection from "@/components/common/ContactSection/ContactSection";
import Footer from "@/components/common/Footer/Footer";

export const metadata = {
  title: "Invent Lift",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {/* <Navbar /> */}
        {/* <Temp /> */}
        {children}
        <ContactSection/>
        <Footer/>
      </body>
    </html>
  );
}
