name: Deploy MERN Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@v0.1.6
        timeout-minutes: 60 
        with:
          timeout: 1h       # ← THIS is likely the culprit!
          command_timeout: 1h # ← ADD THIS LINE
          host: ${{ secrets.SERVER_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /home/ec2-user/web-apps/Invent-Elevators
            git fetch origin main
            git reset --hard origin/main

            docker-compose down
            docker-compose up -d --build

            docker image prune -f